using System.Text;
using GraniteBiDeployWizard.Models;

namespace GraniteBiDeployWizard.Core;

/// <summary>
/// Generates the .bat wrapper that the scheduled task runs. It uses sqlcmd's
/// -E switch (trusted/integrated authentication) so no password is ever
/// written into the file -- the Windows account the task runs as (Panel 5)
/// is what actually authenticates to SQL Server.
/// </summary>
public static class BatchFileGenerator
{
    public static string Generate(DeploymentContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine("@echo off");
        sb.AppendLine("rem ===========================================================================");
        sb.AppendLine("rem  GraniteWMS BI background sync wrapper -- generated by the BI Deployment Wizard");
        sb.AppendLine($"rem  Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("rem  Runs bi.usp_RunSync against the BI database using trusted (-E) auth, under");
        sb.AppendLine("rem  whichever Windows account the scheduled task is configured to run as.");
        sb.AppendLine("rem  No SQL credentials are stored in this file.");
        sb.AppendLine("rem ===========================================================================");
        sb.AppendLine("setlocal");
        sb.AppendLine();
        sb.AppendLine($"sqlcmd -S \"{context.Server}\" -d \"{context.BiDb}\" -E -b -Q \"EXEC bi.usp_RunSync;\"");
        sb.AppendLine();
        sb.AppendLine("set EXITCODE=%ERRORLEVEL%");
        sb.AppendLine("endlocal & exit /b %EXITCODE%");

        return sb.ToString();
    }

    /// <summary>Writes the generated wrapper into the (already normalized) script folder.</summary>
    public static string WriteToScriptFolder(DeploymentContext context)
    {
        string path = context.BuildBatchFilePath();
        File.WriteAllText(path, Generate(context), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        return path;
    }
}
